---
- name: Ansible playbook
  hosts: all

  environment:
    RBENV_ROOT: "{{ rbenv_dir }}"
    PATH: "{{ rbenv_dir }}/bin:{{ rbenv_dir }}/shims:{{ rbenv_dir }}/plugins/ruby-build/bin:{{ ansible_env.PATH }}"

  collections:
    - community.mysql.mysql_user
    - community.mysql.mysql_db

  pre_tasks:
    - name: Install tools and dependencies
      become: true
      block:
        - name: Update list of available packages
          apt:
            update_cache: true
            cache_valid_time: 86400
            autoclean: true
       
        - name: Install Git & ACL
          apt:
            name:
              - git
              - acl
       
        - name: Install development tools
          apt:
            name: build-essential
       
        - name: Install Ruby dependencies
          apt:
            name:
              - autoconf
              - bison
              - patch
              - rustc
              - libssl-dev 
              - libyaml-dev 
              - libreadline6-dev 
              - zlib1g-dev 
              - libgmp-dev 
              - libncurses5-dev 
              - libffi-dev 
              - libgdbm6 
              - libgdbm-dev 
              - libdb-dev 
              - uuid-dev

        - name: Install pymysql
          become: true
          apt:
            name: python3-pymysql

  tasks:
    - name: Create user redmine
      become: true
      user:
        name: redmine
        home: "{{ redmine_user_home }}"
        state: present
        shell: /bin/bash

    - name: Install Rbenv and Ruby-build before Ruby
      become_user: redmine
      become: true
      block:
        - name: Clone Rbenv repo
          git:
            repo: "https://github.com/rbenv/rbenv.git"
            dest: "{{ rbenv_dir }}"

        - name: Clone Ruby-build repo
          git:
            repo: "https://github.com/rbenv/ruby-build.git"
            dest: "{{ rbenv_dir }}/plugins/ruby-build"

        - name: Configure shell to load Rbenv
          lineinfile:
            path: "{{ redmine_user_home }}/.bashrc"
            line: 'eval "$(~/.rbenv/bin/rbenv init - bash)"'

    - name: Install Ruby 3.1.3
      become_user: redmine
      become: true
      block:
        - name: Install Ruby 3.1.3
          command: "rbenv install 3.1.3 -s"

        - name: Set local Ruby version
          command: "rbenv global 3.1.3 -s"
      
    - name: Download and extract Redmine 5.0.4 repo
      become_user: redmine
      become: true
      unarchive:
        src: "https://github.com/redmine/redmine/archive/refs/tags/5.0.4.tar.gz"
        dest: "{{ redmine_user_home }}/"
        remote_src: true

    - name: Install bundle
      block:
        - name: Install library for MySQL Client 
          become: true
          apt:
            name:
              - default-libmysqlclient-dev
 
        - name: Install bundle as redmine user
          become: true
          become_user: redmine
          command: "bundle install"
          args:
            chdir: "{{ redmine_dir }}"

    - name: Install MySQL server and config root user plugin
      become: true
      block:
        - name: Install MySQL server
          apt:
            name: mysql-server
            state: present

        - name: Update MySQL root password # HACER IDEMPOTENTE
          mysql_user:
            name: root
            login_user: root
            login_password: ''
            login_unix_socket: "{{ login_unix_socket }}" 
            password: "{{ mysql_root_password }}"
            host_all: yes
            check_implicit_admin: yes
            state: present

        - name: Create MySQL user for Redmine
          mysql_user:
            name: "{{ mysql_user }}"
            login_user: root
            login_password: "{{ mysql_root_password }}"
            login_unix_socket: "{{ login_unix_socket }}" 
            password: "{{ mysql_password }}"
            priv: '*.*:ALL'
            host: localhost
            state: present

    - name: Create config files and DB
      become: true
      become_user: redmine 
      block:
        - name: Create database      
          mysql_db:
            name: "{{ mysql_database }}"
            login_user: "{{ mysql_user }}"
            login_password: "{{ mysql_password }}"
            state: present
            collation: utf8mb4_general_ci
            encoding: utf8mb4
          environment:
            RAILS_ENV: production
          register: dbCreation

        - name: Create database.yml from template
          template:
            src: database.j2
            dest: "{{ db_config_dir }}/database.yml"
            force: yes

        - name: Create configuration.yml from template
          template:
            src: configuration.j2
            dest: "{{ db_config_dir }}/configuration.yml"
            force: yes

        - name: Session store secret generation
          command: "bundle exec rake generate_secret_token"
          args:
            chdir: "{{ redmine_dir }}"
          when: dbCreation.changed

        - name: Database schema objects creation
          command: "bundle exec rake db:migrate RAILS_ENV=production"
          args:
            chdir: "{{ redmine_dir }}"
          when: dbCreation.changed

        - name: Load example data for DB
          command: "bundle exec rake redmine:load_default_data RAILS_ENV=production REDMINE_LANG=es"
          args:
            chdir: "{{ redmine_dir }}"
          when: dbCreation.changed

        - name: Boot Puma
          command: "bundle exec rails server -e production"
          args:
            chdir: "{{ redmine_dir }}"

