---
- name: Ansible playbook
  hosts: all

  pre_tasks:
    - name: Install tools and dependencies
      become: yes
      block:
      - name: Update list of available packages
        apt:
          update_cache: yes
          cache_valid_time: 86400
          autoclean: yes

      - name: Install Git & ACL
        apt:
          name:
            - git
            - acl

      - name: Install development tools
        apt:
          name:
            - build-essential

      - name: Install Ruby dependencies
        apt:
          name:
            - autoconf
            - bison
            - patch
            - rustc
            - libssl-dev 
            - libyaml-dev 
            - libreadline6-dev 
            - zlib1g-dev 
            - libgmp-dev 
            - libncurses5-dev 
            - libffi-dev 
            - libgdbm6 
            - libgdbm-dev 
            - libdb-dev 
            - uuid-dev

  tasks:
    - name: Create user redmine
      become: yes
      user:
        name: redmine
        home: "{{ redmine_user_home }}"
        state: present
        shell: /bin/bash

    - name: Installations under redmine user
      become_user: redmine
      become: yes
      block:
        - name: Clone Rbenv repo
          git:
            repo: "https://github.com/rbenv/rbenv.git"
            dest: "{{ redmine_user_home }}/.rbenv"

        - name: Clone Ruby-build repo
          git:
            repo: "https://github.com/rbenv/ruby-build.git"
            dest: "{{ redmine_user_home }}/.rbenv/plugins/ruby-build"

        - name: Configure shell to load Rbenv
          lineinfile:
            path: "{{ redmine_user_home }}/.bashrc"
            line: eval "{{ redmine_user_home }}/.rbenv/bin/rbenv init - bash"

        - name: Install Ruby 3.1.3
          command: "{{ redmine_user_home }}/.rbenv/bin/rbenv install 3.1.3 -s"

        - name: Set local Ruby version
          command: "{{ redmine_user_home }}/.rbenv/bin/rbenv global 3.1.3 -s"
        
             #       - name: checkout Redmine source files
             #         git:
             #           repo: "https://github.com/redmine/redmine"
             #           dest: "{{ redmine_user_home }}"
